name: Azure App Service CI/CD for GoAPI

on:
  push:
    branches:
      - main
      - feature/add-score-api
    paths:
      - "backend/go-api/docker/**"
      - "backend/go-api/src/**"
  pull_request:
    branches:
      - feature/add-score-api
    paths:
      - "backend/go-api/docker/**"
      - "backend/go-api/src/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          echo "${{ secrets.K8S_CONFIG }}" > ./backend/go-api/docker/app/config
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build ./backend/go-api/ -t ${{ secrets.REGISTRY_HOST }}/goapi:${{ github.sha }} -f "backend/go-api/docker/app/Dockerfile"
          docker push ${{ secrets.REGISTRY_HOST }}/goapi:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "giganoto-goapi"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "${{ secrets.REGISTRY_HOST }}/goapi:${{ github.sha }}"
